---
title: "Life Expectancy in Baltimore"
author: "Yifan Zhou"
date: "September 15, 2016"
output: html_document
---
# Lab note:
 1. How to enumerate the block?
 2. What kinds of data should be used?
 3. Right now: Write down the Introduction session (specific question), start the method session.
 


# Scientific Question

Develop a model for predicting life expectancy at birth in Baltimore down to single block resolution with estimates of uncertainty. 

# Preparation
## Dataset (potential predictors)
Demographics: Age, gender, race...

Socioeconomic Characteristics: Income, Employment rate, poverty rate, percent of single-parent households...

Education: Reading proficiency, School absenteeism, adult education attainment... 

Community Built and Social Environment: Alcohol/tobacco store density, juvenile arrest rate, domestic violence rate...

Housing: Lead paint violation rate, energy cut-off rate, vacant building density...

Food Environment: Fast food density, carryout density, corner store density, supermarket proximity...

Health Outcomes: Life expectancy and premature mortality, avertable deaths, top ten casuses of death...

## Explore Data

```{r}

data.census<-read.csv(file="VS-14-Census-2010-2014-1.csv",header=T,skip=1,check.names = F)
rownames(data.census)<-data.census[,1]
data.census<-data.census[,-1]
names(data.census)
head(data.census)

```
